spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/kscache?characterEncoding=utf8mb4
    username: root
    password: root
  cloud:
    function:
      definition: cacheItem; cacheUser; updateUserItem;
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:29092
      bindings:
        cacheUser-out-0:
          destination: user-cache-table
        updateUserItem-in-1:
          destination: user-cache-table
logging:
  level:
    org.apache.kafka: warn

